version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ⬆️
    target-branch: "develop"
    groups:
      github-actions:
        patterns:
          - "*"
  # Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ⬆️
    target-branch: "develop"

  - package-ecosystem: pip
    directory: /examples/count_people_in_zone
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /examples/heatmap_and_track
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /examples/speed_estimation
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /examples/time_in_zone
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /examples/tracking
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /examples/traffic_analysis
    schedule:
      interval: daily
