name: PR Conflict Labeler

on:
  # So that PRs touching the same files as the push are updated
  push:
    branches:
      - main
      - develop
  # So that the `dirtyLabel` is removed if conflicts are resolved
  # We recommend `pull_request_target` so that github secrets are available.
  # In `pull_request` we wouldn't be able to change labels of fork PRs
  pull_request_target:
    types: [synchronize]

permissions:
  pull-requests: write
  issues: write
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - name: check if prs are dirty
        uses: eps1lon/actions-label-merge-conflict@v3
        with:
          dirtyLabel: "has conflicts"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
