name: 🔧 Pytest/Test Workflow

on:
  pull_request:
    branches: [main, develop]

jobs:
  run-tests:
    name: Import Test and Pytest Run
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: 🐍 Install uv and set Python version ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867 # v7.1.6
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: true


      - name: 🚀 Install Packages
        run: uv pip install -r pyproject.toml --group dev --group docs --extra metrics

      - name: 🧪 Run the Import test
        run: uv run python -c "import supervision; from supervision import assets; from supervision import metrics; print(supervision.__version__)"

      - name: 🧪 Run the Test
        run: uv run pytest
